#############################################################
# Tanzu / VKS Cluster Definition
#
# Purpose:
# Define a new VKS cluster that will be deployed into the
# Supervisor Namespace:
#
#   dev-terraform-deployment-ns
#
# Target Cluster:
#   terraform-deployed-cluster-01
#
# ClusterClass:
#   builtin-generic-v3.6.0
#
# Kubernetes Version:
#   v1.35.5+vmware.1
#
#############################################################

apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster

metadata:

  # Name of the Tanzu Kubernetes Cluster
  name: terraform-deployed-cluster-01

  # Supervisor Namespace where the cluster will be deployed
  namespace: dev-terraform-deployment-ns

spec:

  #########################################################
  # Cluster Network Configuration
  #
  # Values copied from the working dev-demo-cluster.
  #
  #########################################################

  clusterNetwork:

    pods:
      cidrBlocks:
      - 192.168.0.0/16

    services:
      cidrBlocks:
      - 10.96.0.0/12

  #########################################################
  # Cluster Topology
  #########################################################

  topology:

    classRef:
      name: builtin-generic-v3.6.0
      namespace: vmware-system-vks-public

    version: v1.35.5+vmware.1

    controlPlane:
      replicas: 1

    workers:
      machineDeployments:
      - class: node-pool
        name: worker
        replicas: 1

    #######################################################
    # Required ClusterClass Variables
    #######################################################

    variables:

    - name: vmClass
      value: best-effort-small

    - name: storageClass
      value: dev-k8-storagepolicy